// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.8
// source: auth_service.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthReqMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MemberId         int64                  `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,2,opt,name=organizationCode,proto3" json:"organizationCode,omitempty"`
	Page             int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthReqMessage) Reset() {
	*x = AuthReqMessage{}
	mi := &file_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReqMessage) ProtoMessage() {}

func (x *AuthReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReqMessage.ProtoReflect.Descriptor instead.
func (*AuthReqMessage) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthReqMessage) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *AuthReqMessage) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *AuthReqMessage) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AuthReqMessage) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ProjectAuth struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,2,opt,name=OrganizationCode,proto3" json:"OrganizationCode,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	CreateAt         string                 `protobuf:"bytes,4,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	Sort             int32                  `protobuf:"varint,5,opt,name=Sort,proto3" json:"Sort,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Desc             string                 `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	CreateBy         int64                  `protobuf:"varint,8,opt,name=CreateBy,proto3" json:"CreateBy,omitempty"`
	IsDefault        int32                  `protobuf:"varint,9,opt,name=IsDefault,proto3" json:"IsDefault,omitempty"`
	Type             string                 `protobuf:"bytes,10,opt,name=Type,proto3" json:"Type,omitempty"`
	CanDelete        int32                  `protobuf:"varint,11,opt,name=CanDelete,proto3" json:"CanDelete,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProjectAuth) Reset() {
	*x = ProjectAuth{}
	mi := &file_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectAuth) ProtoMessage() {}

func (x *ProjectAuth) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectAuth.ProtoReflect.Descriptor instead.
func (*ProjectAuth) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectAuth) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectAuth) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *ProjectAuth) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProjectAuth) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *ProjectAuth) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProjectAuth) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProjectAuth) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ProjectAuth) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *ProjectAuth) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *ProjectAuth) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProjectAuth) GetCanDelete() int32 {
	if x != nil {
		return x.CanDelete
	}
	return 0
}

type ListAuthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ProjectAuth         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthMessage) Reset() {
	*x = ListAuthMessage{}
	mi := &file_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthMessage) ProtoMessage() {}

func (x *ListAuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthMessage.ProtoReflect.Descriptor instead.
func (*ListAuthMessage) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuthMessage) GetList() []*ProjectAuth {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListAuthMessage) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_auth_service_proto protoreflect.FileDescriptor

const file_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x12auth_service.proto\x12\x0fauth.service.v1\"\x88\x01\n" +
	"\x0eAuthReqMessage\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\x03R\bmemberId\x12*\n" +
	"\x10organizationCode\x18\x02 \x01(\tR\x10organizationCode\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"\xa7\x02\n" +
	"\vProjectAuth\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x10OrganizationCode\x18\x02 \x01(\tR\x10OrganizationCode\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12\x1a\n" +
	"\bCreateAt\x18\x04 \x01(\tR\bCreateAt\x12\x12\n" +
	"\x04Sort\x18\x05 \x01(\x05R\x04Sort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x12\n" +
	"\x04desc\x18\a \x01(\tR\x04desc\x12\x1a\n" +
	"\bCreateBy\x18\b \x01(\x03R\bCreateBy\x12\x1c\n" +
	"\tIsDefault\x18\t \x01(\x05R\tIsDefault\x12\x12\n" +
	"\x04Type\x18\n" +
	" \x01(\tR\x04Type\x12\x1c\n" +
	"\tCanDelete\x18\v \x01(\x05R\tCanDelete\"Y\n" +
	"\x0fListAuthMessage\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.auth.service.v1.ProjectAuthR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2^\n" +
	"\vAuthService\x12O\n" +
	"\bAuthList\x12\x1f.auth.service.v1.AuthReqMessage\x1a .auth.service.v1.ListAuthMessage\"\x00B\"Z project-project/pkg/service/authb\x06proto3"

var (
	file_auth_service_proto_rawDescOnce sync.Once
	file_auth_service_proto_rawDescData []byte
)

func file_auth_service_proto_rawDescGZIP() []byte {
	file_auth_service_proto_rawDescOnce.Do(func() {
		file_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_proto_rawDesc), len(file_auth_service_proto_rawDesc)))
	})
	return file_auth_service_proto_rawDescData
}

var file_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_service_proto_goTypes = []any{
	(*AuthReqMessage)(nil),  // 0: auth.service.v1.AuthReqMessage
	(*ProjectAuth)(nil),     // 1: auth.service.v1.ProjectAuth
	(*ListAuthMessage)(nil), // 2: auth.service.v1.ListAuthMessage
}
var file_auth_service_proto_depIdxs = []int32{
	1, // 0: auth.service.v1.ListAuthMessage.list:type_name -> auth.service.v1.ProjectAuth
	0, // 1: auth.service.v1.AuthService.AuthList:input_type -> auth.service.v1.AuthReqMessage
	2, // 2: auth.service.v1.AuthService.AuthList:output_type -> auth.service.v1.ListAuthMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_service_proto_init() }
func file_auth_service_proto_init() {
	if File_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_proto_rawDesc), len(file_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_proto_goTypes,
		DependencyIndexes: file_auth_service_proto_depIdxs,
		MessageInfos:      file_auth_service_proto_msgTypes,
	}.Build()
	File_auth_service_proto = out.File
	file_auth_service_proto_goTypes = nil
	file_auth_service_proto_depIdxs = nil
}
